# BASE
# https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#container-registry-examples

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

###############################################################################
## ENTITY MANAGER DOCKER
###############################################################################

test:
  image: node:12
  stage: test
  cache:
    paths:
      - node_modules
    policy: push
  before_script:
    - npm i
  script:
    - npm test

manager-build:
  image: node:12
  stage: build
  script:
    - npm install
    - npm run export
  #artifacts:
  #  name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  #  paths:
  #    - build/
  except:
    - master
    - release
  cache:
    paths:
      - node_modules
    policy: pull

manager-docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    # Gitlab CI
    # - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    # - docker build --pull -t ${MANAGER_RELEASE_IMAGE} --build-arg "BOOTNODES_URL_READ_ONLY=$BOOTNODES_URL_READ_ONLY" --build-arg "ETH_NETWORK_ID=$ETH_NETWORK_ID" -f Dockerfile .
    # - docker push ${MANAGER_RELEASE_IMAGE}
    #
    # Docker Hub
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    # Plain image
    - docker build -t ${CI_REGISTRY_IMAGE}:latest --build-arg "ETH_NETWORK_ID=$ETH_NETWORK_ID" --build-arg "BOOTNODES_URL_READ_ONLY=$BOOTNODES_URL_READ_ONLY" --build-arg "BOOTNODES_URL_RW=$BOOTNODES_URL_RW" --build-arg "APP_LINKING_DOMAIN=$APP_LINKING_DOMAIN" --build-arg "REGISTER_URL=$REGISTER_URL" --build-arg "ACTION_VISIBILITY_URL=$ACTION_VISIBILITY_URL" --build-arg "MANAGER_BACKEND_URI=$MANAGER_BACKEND_URI" --build-arg "MANAGER_BACKEND_PUB_KEY=$MANAGER_BACKEND_PUB_KEY" .
    - docker push ${CI_REGISTRY_IMAGE}:latest
    # Nginx runtime image
    - docker build --target nginx-runtime -t ${CI_REGISTRY_IMAGE}:nginx-latest --build-arg "ETH_NETWORK_ID=$ETH_NETWORK_ID" --build-arg "BOOTNODES_URL_READ_ONLY=$BOOTNODES_URL_READ_ONLY" --build-arg "BOOTNODES_URL_RW=$BOOTNODES_URL_RW" --build-arg "APP_LINKING_DOMAIN=$APP_LINKING_DOMAIN" --build-arg "REGISTER_URL=$REGISTER_URL" --build-arg "ACTION_VISIBILITY_URL=$ACTION_VISIBILITY_URL" --build-arg "MANAGER_BACKEND_URI=$MANAGER_BACKEND_URI" --build-arg "MANAGER_BACKEND_PUB_KEY=$MANAGER_BACKEND_PUB_KEY" .
    - docker push ${CI_REGISTRY_IMAGE}:nginx-latest
  only:
    changes:
      - components/**/*
      - i18n/**/*
      - lib/**/*
      - pages/**/*
      - public/**/*
      - styles/**/*
      - Dockerfile-live
      - .dockerignore
      - .gitlab-ci.yml
      - env-config.js
      - next.config.js
      - package-lock.json
      - package.json
      - tsconfig.json
    refs:
      - master

manager-docker-release:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    # Gitlab CI
    # - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    # - docker build --pull -t ${MANAGER_RELEASE_IMAGE} --build-arg "BOOTNODES_URL_READ_ONLY=$BOOTNODES_URL_READ_ONLY" --build-arg "ETH_NETWORK_ID=$ETH_NETWORK_ID" -f Dockerfile .
    # - docker push ${MANAGER_RELEASE_IMAGE}
    #
    # Docker Hub
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    # Plain image
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} --build-arg "ETH_NETWORK_ID=$ETH_NETWORK_ID" --build-arg "BOOTNODES_URL_READ_ONLY=$BOOTNODES_URL_READ_ONLY" --build-arg "BOOTNODES_URL_RW=$BOOTNODES_URL_RW" --build-arg "APP_LINKING_DOMAIN=$APP_LINKING_DOMAIN" --build-arg "REGISTER_URL=$REGISTER_URL" --build-arg "ACTION_VISIBILITY_URL=$ACTION_VISIBILITY_URL" --build-arg "MANAGER_BACKEND_URI=$MANAGER_BACKEND_URI" --build-arg "MANAGER_BACKEND_PUB_KEY=$MANAGER_BACKEND_PUB_KEY" .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    # Nginx runtime image
    - docker build --target nginx-runtime -t ${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_REF_NAME} --build-arg "ETH_NETWORK_ID=$ETH_NETWORK_ID" --build-arg "BOOTNODES_URL_READ_ONLY=$BOOTNODES_URL_READ_ONLY" --build-arg "BOOTNODES_URL_RW=$BOOTNODES_URL_RW" --build-arg "APP_LINKING_DOMAIN=$APP_LINKING_DOMAIN" --build-arg "REGISTER_URL=$REGISTER_URL" --build-arg "ACTION_VISIBILITY_URL=$ACTION_VISIBILITY_URL" --build-arg "MANAGER_BACKEND_URI=$MANAGER_BACKEND_URI" --build-arg "MANAGER_BACKEND_PUB_KEY=$MANAGER_BACKEND_PUB_KEY" .
    - docker push ${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_REF_NAME}

  only:
    changes:
      - components/**/*
      - i18n/**/*
      - lib/**/*
      - pages/**/*
      - public/**/*
      - styles/**/*
      - Dockerfile-live
      - .dockerignore
      - .gitlab-ci.yml
      - env-config.js
      - next.config.js
      - package-lock.json
      - package.json
      - tsconfig.json
    refs:
      - master
      - release
      - /^release-.*$/
      - stage
## PREVIEW

# pages:
#   stage: preview
#   image: alpine:latest
#   environment: staging
#   script:
#   - cp -a ./build ./public
#   artifacts:
#     paths:
#     - public
#   except:
#   - master

# review:
#   stage: deploy
#   image: alpine:latest
#   script:
#     - echo "Deploy to review server"
#   environment:
#     name: review/$CI_COMMIT_REF_NAME
#     # url: https://$CI_ENVIRONMENT_SLUG.example.com/
#   except:
#   - master

## DELIVERY

# variables:
#   S3_BUCKET_NAME: "yourbucket"

# deploy to production:
#   environment: production
#   image: python:latest
#   script:
#   - pip install awscli
#   - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"
#   only:
#   - master
