# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10-alpine

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#
#services:
#  - mongo:4

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
#   paths:
#   - node_modules/

## INTEGRATION

build:
  script:
    - apk --no-cache add --virtual native-deps git
    - npm install
    - npm run export
    - apk del native-deps
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - public/
#   only:
#     - master

# docker build:
#   script: docker build -t voc/entity-manager:$CI_COMMIT_REF_SLUG .
#   only:
#     changes:
#       - Dockerfile
#       - public/**/*

## DELIVERY

pages:
  image: alpine:latest
  environment: staging
  script:
  - cp -a ./build ./public
  artifacts:
    paths:
    - public
#   except:
#   - master


# variables:
#   S3_BUCKET_NAME: "yourbucket"

# deploy to production:
#   environment: production
#   image: python:latest
#   script:
#   - pip install awscli
#   - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"
#   only:
#   - master
