# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

stages:
  - build
  - test
  - preview
  - deploy

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#
#services:
#  - mongo:4

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
#   paths:
#   - node_modules/

## INTEGRATION

build:
  stage: build
  script:
    - npm install
    - npm run export
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/
#   only:
#     - master

# docker build:
#   script: docker build -t voc/entity-manager:$CI_COMMIT_REF_SLUG .
#   only:
#     changes:
#       - Dockerfile
#       - public/**/*

## PREVIEW

pages:
  stage: preview
  image: alpine:latest
  environment: staging
  script:
  - cp -a ./build ./public
  artifacts:
    paths:
    - public
#   except:
#   - master

review:
  stage: deploy
  script:
    - echo "Deploy to review server"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    # url: https://$CI_ENVIRONMENT_SLUG.example.com/
#   environment:
#     name: staging
    # url: https://staging.example.com
#   only:
#   - master

## DELIVERY

# variables:
#   S3_BUCKET_NAME: "yourbucket"

# deploy to production:
#   environment: production
#   image: python:latest
#   script:
#   - pip install awscli
#   - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"
#   only:
#   - master
